#!/bin/bash

### BEGIN INIT INFO
# Provides:          Rosemary portal 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Rosemary portal
# Description:       Rosemary portal
# chkconfig: 235 90 10

### END INIT INFO

# Author: Juan Luis Font <j.l.font@amc.uva.nl>

RETVAL=0

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/
DESC="Rosemary portal"

# dirac monitor user
RM_USER="rosemary"
# getting user $HOME
RM_HOME=`eval echo ~"$RM_USER"`

PIDFILE=$RM_HOME/.rosemary.pid

# program
RM_BINARY="$RM_HOME/Rosemary/target/universal/stage/bin/rosemary"
RM_PARAM="-Dhttp.port=8080 -Dpidfile.path=$PIDFILE"
RM_RUN="nohup $RM_BINARY $RM_PARAM 0<&- &> /dev/null &"


#. /lib/lsb/init-functions
. /etc/rc.d/init.d/functions

# Function that starts the daemon/service
do_start()
{
	echo "Starting $DESC"

	if [[ -f "$PIDFILE" ]]; then
		kill -0 `cat $PIDFILE` &> /dev/null
		if [[ $? -eq 0 ]]; then
			echo "$DESC already running."
			return 1
		fi
	
	fi
    # starting portal
        daemon --user $RM_USER $RM_RUN
	RETVAL=$?

}

# Function that stops the daemon/service
do_stop()
{
	echo "Stopping $DESC"

	if [[ -f "$PIDFILE" ]]; then

		kill -9 `cat $PIDFILE` &> /dev/null
		RETVAL=$?
		[ $RETVAL = 0 ] && rm $PIDFILE
	else
		echo "$DESC was not running"
		return 1
	fi
}

do_restart()
{
	echo "Restarting $DESC" 
	do_stop
	do_start
}

do_status()
{
	if [[ -f $PIDFILE ]]; then
		echo "$DESC is running"
	else
		echo "$DESC is NOT running"
	fi
	
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
	;;
  restart)
	do_restart
    ;;
  status)
    do_status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
	exit 2
    ;;
esac

exit $RETVAL
